### ISSUE TITLE
The Glossary

### ISSUE THREAD

**Issue by SpencerGood1** [robertesposito1996/Toy-Car-Packaging#1]
"Created by" and "Effective Date" aren't really necessary in the glossary as this document acts as a dictionary for the company. You wouldn't see who created a definition next to a word in the Webster dictionary right? Same with the time the word was created. What matters with this document is that the terms are clearly defined and in alphabetic order which is what you already have. A tiny adjustment, but would make it better!

**Comment by rguevara15** [comment]
Change has been made
