### ISSUE TITLE
The Change Request Form

### ISSUE THREAD

**Issue by SpencerGood1** [robertesposito1996/Toy-Car-Packaging#2]
In the Change Request form, it would be ideal if there was a place somewhere to include the dimensions of the product since a Change Request is essentially the form that tells the company what they're about to make. With our document we just put a small section inside the "comments/additional information" section so the user can easily keep track of them.

**Comment by robertesposito1996** [comment]
Just added a dimensions section next to the additional comments section of the Engineering Change Request form.
