### ISSUE TITLE
Dimension Sheet 

### ISSUE THREAD

**Issue by ChrisDoolan** [robertesposito1996/Toy-Car-Packaging#4]
Dimensions on Pack_Plast_Cov_RJE3_1 was over dimension on the plastic holder and profile view. And missing radius dimensions for corners and fillet.

**Comment by robertesposito1996** [comment]
Just adjusted & fixed some of the dimensions of the Pack_Plast_Cov_RJE3_1.  I got rid of a few of unnecessary dimensions so they are a little easier to read.
